# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

resources:
  containers:
  - container: sampleapp
    type: ACR  
    azureSubscription: 'adhocke internal subscription(7effabcc-eb49-42ab-bf6e-f8351cb0f708)'
    resourceGroup: DevOpsPipelinesCodeTesting
    registry: devopstestingahock
    repository: appservicecontainersbluegreen
    trigger: true
#      tags:
#      - latest # tag for the container image to use


steps:
- script: echo |
    echo $(resources.container.sampleapp.type)
    echo $(resources.container.sampleapp.registry)
    echo $(resources.container.sampleapp.repository)
    echo $(resources.container.sampleapp.tag)
    echo $(resources.container.sampleapp.digest)
    echo $(resources.container.sampleapp.URI)
    echo $(resources.container.sampleapp.location)