apiVersion: v1
kind: Service
metadata:
    name: "aksemqxdemoahock-4f65"
    labels:
        app: "aksemqxdemoahock-4f65"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aksemqxdemoahock-4f65"