on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: devopstestingahock.azurecr.io
        username: ${{ secrets.acr_devopstestingahock_username }}
        password: ${{ secrets.acr_devopstestingahock_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t devopstestingahock.azurecr.io/aksemqxdemoahock:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push devopstestingahock.azurecr.io/aksemqxdemoahock:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksemqxdemoahock_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bluegreenapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bluegreenapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bluegreenapp
        container-registry-url: devopstestingahock.azurecr.io
        container-registry-username: ${{ secrets.acr_devopstestingahock_username }}
        container-registry-password: ${{ secrets.acr_devopstestingahock_password }}
        secret-name: aksemqxdemoadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: bluegreenapp
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          devopstestingahock.azurecr.io/aksemqxdemoahock:${{ github.sha }}
        imagepullsecrets: |
          aksemqxdemoadockerauth
